# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NeedleGUI_ui_form_v1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 570))
        MainWindow.setMaximumSize(QtCore.QSize(1120, 570))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spiral_search = QtWidgets.QGroupBox(self.centralwidget)
        self.spiral_search.setGeometry(QtCore.QRect(0, 90, 251, 181))
        self.spiral_search.setObjectName("spiral_search")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.spiral_search)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 30, 231, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.search_button.setCheckable(False)
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.speed_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.speed_input.setObjectName("speed_input")
        self.gridLayout.addWidget(self.speed_input, 0, 1, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.resolution_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolution_label.setObjectName("resolution_label")
        self.gridLayout.addWidget(self.resolution_label, 1, 0, 1, 1)
        self.speed_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_label.setObjectName("speed_label")
        self.gridLayout.addWidget(self.speed_label, 0, 0, 1, 1)
        self.resolution_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.resolution_input.setObjectName("resolution_input")
        self.gridLayout.addWidget(self.resolution_input, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.searching_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.searching_label.setAlignment(QtCore.Qt.AlignCenter)
        self.searching_label.setObjectName("searching_label")
        self.verticalLayout.addWidget(self.searching_label)
        self.emergency_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.emergency_stop_btn.setGeometry(QtCore.QRect(0, 0, 251, 91))
        self.emergency_stop_btn.setObjectName("emergency_stop_btn")
        self.connections = QtWidgets.QGroupBox(self.centralwidget)
        self.connections.setGeometry(QtCore.QRect(780, 0, 271, 281))
        self.connections.setFlat(False)
        self.connections.setCheckable(False)
        self.connections.setObjectName("connections")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.connections)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 251, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gstate_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gstate_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gstate_label.setObjectName("gstate_label")
        self.gridLayout_2.addWidget(self.gstate_label, 0, 0, 1, 1)
        self.gpredict_port_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gpredict_port_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gpredict_port_label.setObjectName("gpredict_port_label")
        self.gridLayout_2.addWidget(self.gpredict_port_label, 2, 0, 1, 1)
        self.gpredict_state_str = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gpredict_state_str.setObjectName("gpredict_state_str")
        self.gridLayout_2.addWidget(self.gpredict_state_str, 0, 1, 1, 1)
        self.serial_state_str = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.serial_state_str.setObjectName("serial_state_str")
        self.gridLayout_2.addWidget(self.serial_state_str, 1, 1, 1, 1)
        self.serial_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.serial_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serial_label.setObjectName("serial_label")
        self.gridLayout_2.addWidget(self.serial_label, 1, 0, 1, 1)
        self.serial_port_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.serial_port_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serial_port_label.setObjectName("serial_port_label")
        self.gridLayout_2.addWidget(self.serial_port_label, 3, 0, 1, 1)
        self.serial_port_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.serial_port_input.setObjectName("serial_port_input")
        self.gridLayout_2.addWidget(self.serial_port_input, 3, 1, 1, 1)
        self.gpredict_port_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gpredict_port_input.setObjectName("gpredict_port_input")
        self.gridLayout_2.addWidget(self.gpredict_port_input, 2, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.connections)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 190, 251, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gpredict_connect_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.gpredict_connect_btn.setObjectName("gpredict_connect_btn")
        self.verticalLayout_3.addWidget(self.gpredict_connect_btn)
        self.serial_connect_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.serial_connect_btn.setObjectName("serial_connect_btn")
        self.verticalLayout_3.addWidget(self.serial_connect_btn)
        self.coordinate_viewer = QtWidgets.QGroupBox(self.centralwidget)
        self.coordinate_viewer.setGeometry(QtCore.QRect(250, 30, 531, 531))
        self.coordinate_viewer.setObjectName("coordinate_viewer")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.coordinate_viewer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-40, 130, 561, 87))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.raw_tgt_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.raw_tgt_layout.setContentsMargins(0, 0, 0, 0)
        self.raw_tgt_layout.setObjectName("raw_tgt_layout")
        self.raw_tgt_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.raw_tgt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.raw_tgt_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_tgt_label.setObjectName("raw_tgt_label")
        self.raw_tgt_layout.addWidget(self.raw_tgt_label)
        self.raw_tgt_az_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.raw_tgt_az_label.setFont(font)
        self.raw_tgt_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_tgt_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_tgt_az_label.setObjectName("raw_tgt_az_label")
        self.raw_tgt_layout.addWidget(self.raw_tgt_az_label)
        self.raw_tgt_el_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.raw_tgt_el_label.setFont(font)
        self.raw_tgt_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_tgt_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_tgt_el_label.setObjectName("raw_tgt_el_label")
        self.raw_tgt_layout.addWidget(self.raw_tgt_el_label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.coordinate_viewer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-40, 50, 561, 87))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.raw_pos_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.raw_pos_layout.setContentsMargins(0, 0, 0, 0)
        self.raw_pos_layout.setObjectName("raw_pos_layout")
        self.raw_pos_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.raw_pos_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.raw_pos_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_pos_label.setObjectName("raw_pos_label")
        self.raw_pos_layout.addWidget(self.raw_pos_label)
        self.raw_pos_az_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.raw_pos_az_label.setFont(font)
        self.raw_pos_az_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.raw_pos_az_label.setMidLineWidth(10)
        self.raw_pos_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_pos_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_pos_az_label.setObjectName("raw_pos_az_label")
        self.raw_pos_layout.addWidget(self.raw_pos_az_label)
        self.raw_pos_el_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.raw_pos_el_label.setFont(font)
        self.raw_pos_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_pos_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.raw_pos_el_label.setObjectName("raw_pos_el_label")
        self.raw_pos_layout.addWidget(self.raw_pos_el_label)
        self.coord_viewer_az_label = QtWidgets.QLabel(self.coordinate_viewer)
        self.coord_viewer_az_label.setGeometry(QtCore.QRect(146, 30, 171, 411))
        self.coord_viewer_az_label.setFrameShape(QtWidgets.QFrame.Box)
        self.coord_viewer_az_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.coord_viewer_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coord_viewer_az_label.setObjectName("coord_viewer_az_label")
        self.coord_viewer_el_label = QtWidgets.QLabel(self.coordinate_viewer)
        self.coord_viewer_el_label.setGeometry(QtCore.QRect(346, 30, 151, 411))
        self.coord_viewer_el_label.setFrameShape(QtWidgets.QFrame.Box)
        self.coord_viewer_el_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.coord_viewer_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.coord_viewer_el_label.setObjectName("coord_viewer_el_label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.coordinate_viewer)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(-40, 420, 561, 87))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.sent_tgt_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.sent_tgt_layout.setContentsMargins(0, 0, 0, 0)
        self.sent_tgt_layout.setObjectName("sent_tgt_layout")
        self.sent_tgt_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.sent_tgt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sent_tgt_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sent_tgt_label.setObjectName("sent_tgt_label")
        self.sent_tgt_layout.addWidget(self.sent_tgt_label)
        self.sent_tgt_az_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.sent_tgt_az_label.setFont(font)
        self.sent_tgt_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sent_tgt_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sent_tgt_az_label.setObjectName("sent_tgt_az_label")
        self.sent_tgt_layout.addWidget(self.sent_tgt_az_label)
        self.sent_tgt_el_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.sent_tgt_el_label.setFont(font)
        self.sent_tgt_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sent_tgt_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sent_tgt_el_label.setObjectName("sent_tgt_el_label")
        self.sent_tgt_layout.addWidget(self.sent_tgt_el_label)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.coordinate_viewer)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(-40, 210, 561, 87))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.auto_offset_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.auto_offset_layout.setContentsMargins(0, 0, 0, 0)
        self.auto_offset_layout.setObjectName("auto_offset_layout")
        self.auto_offset_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.auto_offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.auto_offset_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.auto_offset_label.setObjectName("auto_offset_label")
        self.auto_offset_layout.addWidget(self.auto_offset_label)
        self.auto_offset_az_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.auto_offset_az_label.setFont(font)
        self.auto_offset_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.auto_offset_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.auto_offset_az_label.setObjectName("auto_offset_az_label")
        self.auto_offset_layout.addWidget(self.auto_offset_az_label)
        self.auto_offset_el_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.auto_offset_el_label.setFont(font)
        self.auto_offset_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.auto_offset_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.auto_offset_el_label.setObjectName("auto_offset_el_label")
        self.auto_offset_layout.addWidget(self.auto_offset_el_label)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.coordinate_viewer)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(-40, 330, 561, 87))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.manual_offset_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.manual_offset_layout.setContentsMargins(0, 0, 0, 0)
        self.manual_offset_layout.setObjectName("manual_offset_layout")
        self.manual_offset_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.manual_offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.manual_offset_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.manual_offset_label.setObjectName("manual_offset_label")
        self.manual_offset_layout.addWidget(self.manual_offset_label)
        self.manual_offset_az_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.manual_offset_az_label.setFont(font)
        self.manual_offset_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_offset_az_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.manual_offset_az_label.setObjectName("manual_offset_az_label")
        self.manual_offset_layout.addWidget(self.manual_offset_az_label)
        self.manual_offset_el_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.manual_offset_el_label.setFont(font)
        self.manual_offset_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_offset_el_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.manual_offset_el_label.setObjectName("manual_offset_el_label")
        self.manual_offset_layout.addWidget(self.manual_offset_el_label)
        self.az_offset_hundredup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_hundredup_btn.setGeometry(QtCore.QRect(176, 320, 21, 31))
        self.az_offset_hundredup_btn.setObjectName("az_offset_hundredup_btn")
        self.az_offset_tenup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_tenup_btn.setGeometry(QtCore.QRect(206, 320, 21, 31))
        self.az_offset_tenup_btn.setObjectName("az_offset_tenup_btn")
        self.az_offset_oneup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_oneup_btn.setGeometry(QtCore.QRect(236, 320, 21, 31))
        self.az_offset_oneup_btn.setObjectName("az_offset_oneup_btn")
        self.az_offset_tenthup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_tenthup_btn.setGeometry(QtCore.QRect(276, 320, 21, 31))
        self.az_offset_tenthup_btn.setObjectName("az_offset_tenthup_btn")
        self.el_offset_tenup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_tenup_btn.setGeometry(QtCore.QRect(380, 320, 21, 31))
        self.el_offset_tenup_btn.setObjectName("el_offset_tenup_btn")
        self.el_offset_oneup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_oneup_btn.setGeometry(QtCore.QRect(410, 320, 21, 31))
        self.el_offset_oneup_btn.setObjectName("el_offset_oneup_btn")
        self.el_offset_tenthup_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_tenthup_btn.setGeometry(QtCore.QRect(446, 320, 21, 31))
        self.el_offset_tenthup_btn.setObjectName("el_offset_tenthup_btn")
        self.az_offset_hundreddn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_hundreddn_btn.setGeometry(QtCore.QRect(176, 400, 21, 31))
        self.az_offset_hundreddn_btn.setObjectName("az_offset_hundreddn_btn")
        self.az_offset_tendn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_tendn_btn.setGeometry(QtCore.QRect(206, 400, 21, 31))
        self.az_offset_tendn_btn.setObjectName("az_offset_tendn_btn")
        self.az_offset_onedn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_onedn_btn.setGeometry(QtCore.QRect(236, 400, 21, 31))
        self.az_offset_onedn_btn.setObjectName("az_offset_onedn_btn")
        self.az_offset_tenthdn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.az_offset_tenthdn_btn.setGeometry(QtCore.QRect(276, 400, 21, 31))
        self.az_offset_tenthdn_btn.setObjectName("az_offset_tenthdn_btn")
        self.el_offset_tendn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_tendn_btn.setGeometry(QtCore.QRect(380, 400, 21, 31))
        self.el_offset_tendn_btn.setObjectName("el_offset_tendn_btn")
        self.el_offset_onedn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_onedn_btn.setGeometry(QtCore.QRect(410, 400, 21, 31))
        self.el_offset_onedn_btn.setObjectName("el_offset_onedn_btn")
        self.el_offset_tenthdn_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.el_offset_tenthdn_btn.setGeometry(QtCore.QRect(446, 400, 21, 31))
        self.el_offset_tenthdn_btn.setObjectName("el_offset_tenthdn_btn")
        self.auto_offset_reset_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.auto_offset_reset_btn.setGeometry(QtCore.QRect(46, 270, 90, 21))
        self.auto_offset_reset_btn.setObjectName("auto_offset_reset_btn")
        self.manual_offset_el_minus = QtWidgets.QLabel(self.coordinate_viewer)
        self.manual_offset_el_minus.setGeometry(QtCore.QRect(356, 330, 16, 78))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.manual_offset_el_minus.setFont(font)
        self.manual_offset_el_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_offset_el_minus.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.manual_offset_el_minus.setObjectName("manual_offset_el_minus")
        self.auto_offset_el_minus = QtWidgets.QLabel(self.coordinate_viewer)
        self.auto_offset_el_minus.setGeometry(QtCore.QRect(356, 210, 16, 78))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.auto_offset_el_minus.setFont(font)
        self.auto_offset_el_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.auto_offset_el_minus.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.auto_offset_el_minus.setObjectName("auto_offset_el_minus")
        self.auto_offset_az_minus = QtWidgets.QLabel(self.coordinate_viewer)
        self.auto_offset_az_minus.setGeometry(QtCore.QRect(156, 210, 16, 78))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.auto_offset_az_minus.setFont(font)
        self.auto_offset_az_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.auto_offset_az_minus.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.auto_offset_az_minus.setObjectName("auto_offset_az_minus")
        self.manual_offset_az_minus = QtWidgets.QLabel(self.coordinate_viewer)
        self.manual_offset_az_minus.setGeometry(QtCore.QRect(151, 330, 16, 78))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(48)
        self.manual_offset_az_minus.setFont(font)
        self.manual_offset_az_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_offset_az_minus.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.manual_offset_az_minus.setObjectName("manual_offset_az_minus")
        self.raw_tgt_reset_btn = QtWidgets.QPushButton(self.coordinate_viewer)
        self.raw_tgt_reset_btn.setGeometry(QtCore.QRect(46, 190, 90, 21))
        self.raw_tgt_reset_btn.setObjectName("raw_tgt_reset_btn")
        self.position_override = QtWidgets.QGroupBox(self.centralwidget)
        self.position_override.setGeometry(QtCore.QRect(0, 270, 251, 111))
        self.position_override.setObjectName("position_override")
        self.gridLayoutWidget = QtWidgets.QWidget(self.position_override)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.override_az_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.override_az_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.override_az_label.setObjectName("override_az_label")
        self.gridLayout_3.addWidget(self.override_az_label, 0, 0, 1, 1)
        self.override_az_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.override_az_btn.setObjectName("override_az_btn")
        self.gridLayout_3.addWidget(self.override_az_btn, 0, 2, 1, 1)
        self.override_az_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.override_az_input.setObjectName("override_az_input")
        self.gridLayout_3.addWidget(self.override_az_input, 0, 1, 1, 1)
        self.override_el_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.override_el_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.override_el_label.setObjectName("override_el_label")
        self.gridLayout_3.addWidget(self.override_el_label, 1, 0, 1, 1)
        self.override_el_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.override_el_input.setObjectName("override_el_input")
        self.gridLayout_3.addWidget(self.override_el_input, 1, 1, 1, 1)
        self.override_el_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.override_el_btn.setObjectName("override_el_btn")
        self.gridLayout_3.addWidget(self.override_el_btn, 1, 2, 1, 1)
        self.unwind = QtWidgets.QGroupBox(self.centralwidget)
        self.unwind.setGeometry(QtCore.QRect(780, 280, 271, 111))
        self.unwind.setObjectName("unwind")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.unwind)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 241, 36))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.unwind_ccw_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.unwind_ccw_btn.setObjectName("unwind_ccw_btn")
        self.gridLayout_4.addWidget(self.unwind_ccw_btn, 0, 0, 1, 1)
        self.unwind_cw_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.unwind_cw_btn.setObjectName("unwind_cw_btn")
        self.gridLayout_4.addWidget(self.unwind_cw_btn, 0, 1, 1, 1)
        self.unwind_stop_btn = QtWidgets.QPushButton(self.unwind)
        self.unwind_stop_btn.setGeometry(QtCore.QRect(90, 70, 88, 34))
        self.unwind_stop_btn.setObjectName("unwind_stop_btn")
        self.motor_state = QtWidgets.QGroupBox(self.centralwidget)
        self.motor_state.setGeometry(QtCore.QRect(0, 390, 251, 111))
        self.motor_state.setObjectName("motor_state")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.motor_state)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 231, 80))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.enabled_state_el_btn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.enabled_state_el_btn.setObjectName("enabled_state_el_btn")
        self.gridLayout_5.addWidget(self.enabled_state_el_btn, 1, 1, 1, 1)
        self.enabled_state_az_btn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.enabled_state_az_btn.setObjectName("enabled_state_az_btn")
        self.gridLayout_5.addWidget(self.enabled_state_az_btn, 1, 0, 1, 1)
        self.enabled_state_az_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.enabled_state_az_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enabled_state_az_label.setObjectName("enabled_state_az_label")
        self.gridLayout_5.addWidget(self.enabled_state_az_label, 0, 0, 1, 1)
        self.enabled_state_el_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.enabled_state_el_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enabled_state_el_label.setObjectName("enabled_state_el_label")
        self.gridLayout_5.addWidget(self.enabled_state_el_label, 0, 1, 1, 1)
        self.gs_connected_label = QtWidgets.QLabel(self.centralwidget)
        self.gs_connected_label.setGeometry(QtCore.QRect(260, 10, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.gs_connected_label.setFont(font)
        self.gs_connected_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gs_connected_label.setObjectName("gs_connected_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NeedleGUI"))
        self.spiral_search.setTitle(_translate("MainWindow", "Spiral Search Tool"))
        self.search_button.setText(_translate("MainWindow", "Start Search"))
        self.speed_input.setText(_translate("MainWindow", "1"))
        self.resolution_label.setText(_translate("MainWindow", "Resolution"))
        self.speed_label.setText(_translate("MainWindow", "Speed"))
        self.resolution_input.setText(_translate("MainWindow", "1"))
        self.searching_label.setText(_translate("MainWindow", "SPIRAL SEARCHING"))
        self.emergency_stop_btn.setText(_translate("MainWindow", "EMERGENCY STOP"))
        self.connections.setTitle(_translate("MainWindow", "Connections"))
        self.gstate_label.setText(_translate("MainWindow", "Gpredict State:"))
        self.gpredict_port_label.setText(_translate("MainWindow", "Gpredict Port"))
        self.gpredict_state_str.setText(_translate("MainWindow", "Disconnected"))
        self.serial_state_str.setText(_translate("MainWindow", "Disconnected"))
        self.serial_label.setText(_translate("MainWindow", "Serial State:"))
        self.serial_port_label.setText(_translate("MainWindow", "Serial Port"))
        self.gpredict_connect_btn.setText(_translate("MainWindow", "Open Gpredict Connection"))
        self.serial_connect_btn.setText(_translate("MainWindow", "Open Serial Connection"))
        self.coordinate_viewer.setTitle(_translate("MainWindow", "Coordinate Viewer"))
        self.raw_tgt_label.setText(_translate("MainWindow", "RAW TARGET:"))
        self.raw_tgt_az_label.setText(_translate("MainWindow", "000.0"))
        self.raw_tgt_el_label.setText(_translate("MainWindow", "00.0"))
        self.raw_pos_label.setText(_translate("MainWindow", "RAW POSITION:"))
        self.raw_pos_az_label.setText(_translate("MainWindow", "000.0"))
        self.raw_pos_el_label.setText(_translate("MainWindow", "00.0"))
        self.coord_viewer_az_label.setText(_translate("MainWindow", "AZIMUTH"))
        self.coord_viewer_el_label.setText(_translate("MainWindow", "ELEVATION"))
        self.sent_tgt_label.setText(_translate("MainWindow", "SENT TARGET:"))
        self.sent_tgt_az_label.setText(_translate("MainWindow", "000.0"))
        self.sent_tgt_el_label.setText(_translate("MainWindow", "00.0"))
        self.auto_offset_label.setText(_translate("MainWindow", "AUTOMATIC OFFSET:"))
        self.auto_offset_az_label.setText(_translate("MainWindow", "000.0"))
        self.auto_offset_el_label.setText(_translate("MainWindow", "00.0"))
        self.manual_offset_label.setText(_translate("MainWindow", "MANUAL OFFSET:"))
        self.manual_offset_az_label.setText(_translate("MainWindow", "000.0"))
        self.manual_offset_el_label.setText(_translate("MainWindow", "00.0"))
        self.az_offset_hundredup_btn.setText(_translate("MainWindow", "↑"))
        self.az_offset_tenup_btn.setText(_translate("MainWindow", "↑"))
        self.az_offset_oneup_btn.setText(_translate("MainWindow", "↑"))
        self.az_offset_tenthup_btn.setText(_translate("MainWindow", "↑"))
        self.el_offset_tenup_btn.setText(_translate("MainWindow", "↑"))
        self.el_offset_oneup_btn.setText(_translate("MainWindow", "↑"))
        self.el_offset_tenthup_btn.setText(_translate("MainWindow", "↑"))
        self.az_offset_hundreddn_btn.setText(_translate("MainWindow", "↓"))
        self.az_offset_tendn_btn.setText(_translate("MainWindow", "↓"))
        self.az_offset_onedn_btn.setText(_translate("MainWindow", "↓"))
        self.az_offset_tenthdn_btn.setText(_translate("MainWindow", "↓"))
        self.el_offset_tendn_btn.setText(_translate("MainWindow", "↓"))
        self.el_offset_onedn_btn.setText(_translate("MainWindow", "↓"))
        self.el_offset_tenthdn_btn.setText(_translate("MainWindow", "↓"))
        self.auto_offset_reset_btn.setText(_translate("MainWindow", "RESET"))
        self.manual_offset_el_minus.setText(_translate("MainWindow", "-"))
        self.auto_offset_el_minus.setText(_translate("MainWindow", "-"))
        self.auto_offset_az_minus.setText(_translate("MainWindow", "-"))
        self.manual_offset_az_minus.setText(_translate("MainWindow", "-"))
        self.raw_tgt_reset_btn.setText(_translate("MainWindow", "RESET"))
        self.position_override.setToolTip(_translate("MainWindow", "Click \"Override\" to set the onboard position to the value in the input box"))
        self.position_override.setTitle(_translate("MainWindow", "Position Override"))
        self.override_az_label.setText(_translate("MainWindow", "Azimuth:"))
        self.override_az_btn.setText(_translate("MainWindow", "Override"))
        self.override_az_input.setText(_translate("MainWindow", "0"))
        self.override_el_label.setText(_translate("MainWindow", "Elevation:"))
        self.override_el_input.setText(_translate("MainWindow", "0"))
        self.override_el_btn.setText(_translate("MainWindow", "Override"))
        self.unwind.setTitle(_translate("MainWindow", "Unwind Tool"))
        self.unwind_ccw_btn.setText(_translate("MainWindow", "CCW Unwind"))
        self.unwind_cw_btn.setText(_translate("MainWindow", "CW Unwind"))
        self.unwind_stop_btn.setText(_translate("MainWindow", "STOP"))
        self.motor_state.setTitle(_translate("MainWindow", "Motor State"))
        self.enabled_state_el_btn.setText(_translate("MainWindow", "Disable EL"))
        self.enabled_state_az_btn.setText(_translate("MainWindow", "Disable AZ"))
        self.enabled_state_az_label.setText(_translate("MainWindow", "Azimuth Enabled"))
        self.enabled_state_el_label.setText(_translate("MainWindow", "Eleveation Enabled"))
        self.gs_connected_label.setText(_translate("MainWindow", "GS CONTROLLER NOT CONNECTED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
